[project]
name = "multimodal-language-model"
version = "0.1.0"
description = ""
authors = [
    {name = "narendramall",email = "narendramall.iitkgp@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "torch (==2.3.0)",
    "torchvision (==0.18.0)",
    "torchaudio (==2.3.0)",
    "fire (==0.6.0)",
    "numpy (==1.26.4)",
    "pillow (==10.3.0)",
    "safetensors (==0.4.3)",
    "tokenizers (==0.19.1)",
    "tqdm (==4.66.4)",
    "transformers (==4.41.2)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
